#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BP_MODULES 1
#define CPTCFG_BPAUTO_NEW_LEDS 1
#define CPTCFG_BPAUTO_LEDS_CLASS 1
#define CPTCFG_BPAUTO_LEDS_TRIGGERS 1
#define CPTCFG_BPAUTO_SYSTEM_DATA_VERIFICATION 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_CFG80211_REQUIRE_SIGNED_REGDB 1
#define CPTCFG_CFG80211_USE_KERNEL_REGDB_KEYS 1
#define CPTCFG_CFG80211_DEFAULT_PS 1
#define CPTCFG_CFG80211_CRDA_SUPPORT 1
#define CPTCFG_CFG80211_WEXT 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_HAS_RC 1
#define CPTCFG_MAC80211_RC_MINSTREL 1
#define CPTCFG_MAC80211_RC_MINSTREL_HT 1
#define CPTCFG_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT "minstrel_ht"
#define CPTCFG_MAC80211_MESH 1
#define CPTCFG_MAC80211_LEDS 1
#define CPTCFG_MAC80211_STA_HASH_MAX_SIZE 0
#define CPTCFG_WLAN 1
#define CPTCFG_ATH_COMMON_MODULE 1
#define CPTCFG_WLAN_VENDOR_ATH 1
#define CPTCFG_ATH9K_HW_MODULE 1
#define CPTCFG_ATH9K_COMMON_MODULE 1
#define CPTCFG_ATH9K_BTCOEX_SUPPORT 1
#define CPTCFG_ATH9K_MODULE 1
#define CPTCFG_ATH9K_PCI 1
#define CPTCFG_ATH9K_RFKILL 1
#define CPTCFG_ATH9K_PCOEM 1
#define CPTCFG_ATH9K_HTC_MODULE 1
#define CPTCFG_BACKPORTED_WIRELESS 1
#define CPTCFG_BACKPORTED_NET_CORE 1
#define CPTCFG_BACKPORTED_EXPERT 1
#define CPTCFG_BACKPORTED_BP_MODULES 1
#define CPTCFG_BACKPORTED_BPAUTO_NEW_LEDS 1
#define CPTCFG_BACKPORTED_BPAUTO_LEDS_CLASS 1
#define CPTCFG_BACKPORTED_BPAUTO_LEDS_TRIGGERS 1
#define CPTCFG_BACKPORTED_BPAUTO_SYSTEM_DATA_VERIFICATION 1
#define CPTCFG_BACKPORTED_CFG80211_MODULE 1
#define CPTCFG_BACKPORTED_CFG80211_REQUIRE_SIGNED_REGDB 1
#define CPTCFG_BACKPORTED_CFG80211_USE_KERNEL_REGDB_KEYS 1
#define CPTCFG_BACKPORTED_CFG80211_DEFAULT_PS 1
#define CPTCFG_BACKPORTED_CFG80211_CRDA_SUPPORT 1
#define CPTCFG_BACKPORTED_CFG80211_WEXT 1
#define CPTCFG_BACKPORTED_MAC80211_MODULE 1
#define CPTCFG_BACKPORTED_MAC80211_HAS_RC 1
#define CPTCFG_BACKPORTED_MAC80211_RC_MINSTREL 1
#define CPTCFG_BACKPORTED_MAC80211_RC_MINSTREL_HT 1
#define CPTCFG_BACKPORTED_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_BACKPORTED_MAC80211_MESH 1
#define CPTCFG_BACKPORTED_MAC80211_LEDS 1
#define CPTCFG_BACKPORTED_WLAN 1
#define CPTCFG_BACKPORTED_ATH_COMMON_MODULE 1
#define CPTCFG_BACKPORTED_WLAN_VENDOR_ATH 1
#define CPTCFG_BACKPORTED_ATH9K_HW_MODULE 1
#define CPTCFG_BACKPORTED_ATH9K_COMMON_MODULE 1
#define CPTCFG_BACKPORTED_ATH9K_BTCOEX_SUPPORT 1
#define CPTCFG_BACKPORTED_ATH9K_MODULE 1
#define CPTCFG_BACKPORTED_ATH9K_PCI 1
#define CPTCFG_BACKPORTED_ATH9K_RFKILL 1
#define CPTCFG_BACKPORTED_ATH9K_PCOEM 1
#define CPTCFG_BACKPORTED_ATH9K_HTC_MODULE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
